### ISSUE TITLE
[BUG] Failing to start

### ISSUE THREAD

**Issue by bewbylover** [jbsparrow/CyberDropDownloader#161]
**Describe the bug**
Application is failing to start, see console output below.

**To Help Reproduce**
Steps to help reproduce the behavior:
1. Start the application

**Screenshots**

**Setup Information**
 - OS: Ubuntu 20.04.6 LTS
 - python 3.11.10
 - Cyberdrop Downloader Version # 5.6.51

**Downloader.log file**
N/A it is not getting that far.

**Additional context**
From the screen:

Traceback (most recent call last):
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/bin/cyberdrop-dl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 173, in main
    manager = startup()
              ^^^^^^^^^
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 26, in startup
    manager.startup()
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/managers/manager.py", line 65, in startup
    self.config_manager.startup()
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/managers/config_manager.py", line 79, in startup
    self.load_configs()
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/managers/config_manager.py", line 100, in load_configs
    self._verify_settings_config()
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/managers/config_manager.py", line 127, in _verify_settings_config
    existing_settings_data = _load_yaml(self.settings)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/cyberdrop_dl/managers/config_manager.py", line 36, in _load_yaml
    yaml_values = yaml.load(yaml_file.read(), Loader=yaml.FullLoader)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kris/Downloads/Cyberdrop_DL.V5.1/venv/lib/python3.11/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:pathlib.PosixPath'
  in "<unicode string>", line 49, column 16:
      scan_folder: !!python/object/apply:pathlib.Po ... 
                   ^

**Comment by jbsparrow** [comment]
You should be on Python 3.11.

**Comment by bewbylover** [comment]
I mistyped it is 3.11.10, I edited the start script to show it with $PYTHON --version:

$ ./"Start Linux.sh" 
Python 3.11.10
Attempting to start venv

**Comment by crimzind** [comment]
I'm getting an issue running, too. Was working yesterday.

**Comment by NTFSvolume** [comment]
The default config file was corrupted. The `scan_folder` value is invalid.

To fix it, please edit it manually and remove `!!python....` from `scan_folder`

Before:
```yaml
Sorting:
  scan_folder: !!python/object/apply:pathlib.Po
  - None
  sort_cdl_only: true
```
After:
```yaml
Sorting:
  scan_folder: None
  sort_cdl_only: true
```

The default config_file is located at `./AppData/Configs/Default/settings.yaml`

**Comment by bewbylover** [comment]
+1 worked for me too

**Comment by crimzind** [comment]
Also worked here, thank you.

**Comment by crazydavebacon** [comment]
getting same errors, works perfect yesterday, broken today. I cant find this specific file to edit, im not savvy in this stuff here, will there be a fix to this in a new update?

**Comment by dsabharwal326** [comment]
What is the equivalent for MacOS?

**Comment by jbsparrow** [comment]
The same fix works on MacOS.
