### ISSUE TITLE
[BUG] failing to start

### ISSUE THREAD

**Issue by dsabharwal326** [jbsparrow/CyberDropDownloader#163]
I'm having a problem with trying to start the software today. I am on MacOS Sonoma 14.1 and using the latest version. Here is the error I am getting:

Traceback (most recent call last):
  File "/Users/deepak/Downloads/Cyberdrop_DL.V5/venv/bin/cyberdrop-dl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/deepak/Downloads/Cyberdrop_DL.V5/venv/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 173, in main
    manager = startup()
              ^^^^^^^^^
  File "/Users/deepak/Downloads/Cyberdrop_DL.V5/venv/lib/python3.11/site-packages/cyberdrop_dl/main.py", line 26, in startup
    manager.startup()
  File "/Users/deepak/Downloads/Cyberdrop_DL.V5/venv/lib/python3.11/site-packages/cyberdrop_dl/managers/manager.py", line 65, in startup
    self.config_manager.startup()
  File "/Users/deepak/Downloads/Cyberdrop_DL.V5/venv/lib/python3.11/site-packages/cyberdrop_dl/managers/config_manager.py", line 79, in startup
    self.load_configs()
  File "/Users/deepak/Downloads/Cyberdrop_DL.V5/venv/lib/python3.11/site-packages/cyberdrop_dl/managers/config_manager.py", line 100, in load_configs
    self._verify_settings_config()
  File "/Users/deepak/Downloads/Cyberdrop_DL.V5/venv/lib/python3.11/site-packages/cyberdrop_dl/managers/config_manager.py", line 127, in _verify_settings_config
    existing_settings_data = _load_yaml(self.settings)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deepak/Downloads/Cyberdrop_DL.V5/venv/lib/python3.11/site-packages/cyberdrop_dl/managers/config_manager.py", line 36, in _load_yaml
    yaml_values = yaml.load(yaml_file.read(), Loader=yaml.FullLoader)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deepak/Downloads/Cyberdrop_DL.V5/venv/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deepak/Downloads/Cyberdrop_DL.V5/venv/lib/python3.11/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deepak/Downloads/Cyberdrop_DL.V5/venv/lib/python3.11/site-packages/yaml/constructor.py", line 60, in construct_document
    for dummy in generator:
  File "/Users/deepak/Downloads/Cyberdrop_DL.V5/venv/lib/python3.11/site-packages/yaml/constructor.py", line 413, in construct_yaml_map
    value = self.construct_mapping(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deepak/Downloads/Cyberdrop_DL.V5/venv/lib/python3.11/site-packages/yaml/constructor.py", line 218, in construct_mapping
    return super().construct_mapping(node, deep=deep)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deepak/Downloads/Cyberdrop_DL.V5/venv/lib/python3.11/site-packages/yaml/constructor.py", line 143, in construct_mapping
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deepak/Downloads/Cyberdrop_DL.V5/venv/lib/python3.11/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/deepak/Downloads/Cyberdrop_DL.V5/venv/lib/python3.11/site-packages/yaml/constructor.py", line 427, in construct_undefined
    raise ConstructorError(None, None,
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:pathlib.PosixPath'
  in "<unicode string>", line 49, column 16:
      scan_folder: !!python/object/apply:pathlib.Po ...

**Comment by chidi9901** [comment]
https://github.com/jbsparrow/CyberDropDownloader/issues/161#issuecomment-2406483211

**Comment by GarethFreeman** [comment]
Same here.
