### ISSUE TITLE
[BUG] `File "<frozen _sitebuiltins>", line 26, in __call__` error in version 5.7.0.dev21

### ISSUE THREAD

**Issue by baccccccc** [jbsparrow/CyberDropDownloader#190]
I'm trying version 5.7.0.dev21 (as suggested in #175). Even if I simply launch the app with no command line arguments and exit immediately, I receive the following error message. This was not the case on 5.6.54.

```
Cyberdrop Downloader (V5.7.0.dev21)
Current Config: Default
? What would you like to do? Exit
Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\main.py", line 48, in startup
    program_ui(manager)
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\ui\ui.py", line 220, in program_ui
    exit(0)
  File "<frozen _sitebuiltins>", line 26, in __call__
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\main.py", line 222, in <module>
    main()
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\main.py", line 204, in main
    manager = startup()
              ^^^^^^^^^
  File "C:\Users\<username>\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\cyberdrop_dl\main.py", line 52, in startup
    except InvalidYamlConfig as e:
           ^^^^^^^^^^^^^^^^^
NameError: name 'InvalidYamlConfig' is not defined
```

**Comment by jbsparrow** [comment]
Fixed in `5.7.0.dev22`.
