### ISSUE TITLE
[BUG] Opening INPUT_FILE with write permissions causing error upon io redirection

### ISSUE THREAD

**Issue by Barbarella6666666** [jbsparrow/CyberDropDownloader#196]
**Describe the bug**
When redirecting the links from clipboard on my MacOS with the command:
cyberdrop-dl --download -i <(pbpaste | grep bunkr)

All files are downloaded properly but it throws the following error at the end:

Traceback (most recent call last):
  File "/Users/my_user/.local/bin/cyberdrop-dl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/my_user/.local/pipx/venvs/cyberdrop-dl-patched/lib/python3.12/site-packages/cyberdrop_dl/main.py", line 183, in main
    asyncio.run(director(manager))
  File "/usr/local/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/my_user/.local/pipx/venvs/cyberdrop-dl-patched/lib/python3.12/site-packages/cyberdrop_dl/main.py", line 153, in director
    await manager.log_manager.update_last_forum_post()
  File "/Users/my_user/.local/pipx/venvs/cyberdrop-dl-patched/lib/python3.12/site-packages/cyberdrop_dl/managers/log_manager.py", line 88, in update_last_forum_post
    async with aiofiles.open(input_file, 'w') as f:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/my_user/.local/pipx/venvs/cyberdrop-dl-patched/lib/python3.12/site-packages/aiofiles/base.py", line 78, in __aenter__
    self._obj = await self._coro
                ^^^^^^^^^^^^^^^^
  File "/Users/my_user/.local/pipx/venvs/cyberdrop-dl-patched/lib/python3.12/site-packages/aiofiles/threadpool/__init__.py", line 80, in _open
    f = yield from loop.run_in_executor(executor, cb)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/dev/fd/13'

**Comment by jbsparrow** [comment]
I'll look into fixing that by checking permissions first, but for now try this command: `cyberdrop-dl --download "$(pbpaste | sed -n '/bunkr/p')"`
