### ISSUE TITLE
[BUG] pycryptodomex subprocess-exited-with-error

### ISSUE THREAD

**Issue by Wolfeman0101** [jbsparrow/CyberDropDownloader#329]
When trying to install via the batch script I get the following error.  Everything works up until this point.  I'm on Windows 11 ARM64 and Python 3.11.4:

`Collecting pycryptodomex<4.0.0,>=3.21.0 (from cyberdrop-dl-patched<6.0,>=5.7)
  Using cached pycryptodomex-3.21.0.tar.gz (4.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      Testing support for clang
      Traceback (most recent call last):
        File "C:\Users\bkwol\Downloads\Cyberdrop-DL v5\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\bkwol\Downloads\Cyberdrop-DL v5\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bkwol\Downloads\Cyberdrop-DL v5\venv\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bkwol\AppData\Local\Temp\pip-build-env-q_j3j5_j\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bkwol\AppData\Local\Temp\pip-build-env-q_j3j5_j\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
        File "C:\Users\bkwol\AppData\Local\Temp\pip-build-env-q_j3j5_j\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 496, in <module>
        File "C:\Users\bkwol\AppData\Local\Temp\pip-install-6_yimqso\pycryptodomex_9620c23fcab843a5b6436080cda7fb10\compiler_opt.py", line 333, in set_compiler_options
          clang = compiler_is_clang()
                  ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bkwol\AppData\Local\Temp\pip-install-6_yimqso\pycryptodomex_9620c23fcab843a5b6436080cda7fb10\compiler_opt.py", line 257, in compiler_is_clang
          return test_compilation(source, msg="clang")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bkwol\AppData\Local\Temp\pip-install-6_yimqso\pycryptodomex_9620c23fcab843a5b6436080cda7fb10\compiler_opt.py", line 82, in test_compilation
          objects = compiler.compile([fname], extra_postargs=extra_cc_options)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bkwol\AppData\Local\Temp\pip-build-env-q_j3j5_j\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 379, in compile
          self.initialize()
        File "C:\Users\bkwol\AppData\Local\Temp\pip-build-env-q_j3j5_j\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 289, in initialize
          vc_env = _get_vc_env(plat_spec)
                   ^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\bkwol\AppData\Local\Temp\pip-build-env-q_j3j5_j\overlay\Lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 150, in _get_vc_env
          raise DistutilsPlatformError(
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Press any key to continue . . .`

**Comment by NTFSvolume** [comment]
Almost none of the dependencies have binaries for ARM64. You need to compile the binaries but your computer does not have any tools to do it.

The error is telling you install Microsoft C++ Build Tools. You can try that but even after installing it, you will probably need to install additional programs.

In any case, this is not an error from CyberDrop-DL. You have to do research on your own on how to build dependencies if you want to run it on ARM64
